LCD-49511 Update echo to not log HTTP status code fragment

diff --git a/cloud/helm/aws/values.yaml b/cloud/helm/aws/values.yaml
--- a/cloud/helm/aws/values.yaml
+++ b/cloud/helm/aws/values.yaml
@@ -64,7 +64,7 @@ liferay-default:
 
                                         if [ "${http_code}" != "200" ]
                                         then
-                                            echo "Unable to download OpenSearch modules for product version ${product_version}. Status code: ${http_code}" >&2
+                                            echo "Unable to download OpenSearch modules for product version ${product_version}." >&2
 
                                             exit 1
                                         fi
